import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutShell from "@/components/LayoutShell";
import SessionProviderWrapper from "@/components/SessionProviderWraper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Auction",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/context/ThemeContext";

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} max-w-[1400px] mx-auto`}>
        <SessionProviderWrapper session={session}>
          <ThemeProvider>
            <LayoutShell>{children}</LayoutShell>
          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
 